import { useEffect, useMemo, useState } from 'react'
import { ChevronLeft, CheckCircle2, Flame, Home, Lightbulb, RotateCcw, Sparkles, Star, Trophy, Volume2, VolumeX, BarChart3 } from 'lucide-react'
import { allLessons, curriculum } from './curriculum'
const rnd=(a,b)=>Math.floor(Math.random()*(b-a+1))+a, pick=a=>a[rnd(0,a.length-1)], shuffle=a=>[...a].sort(()=>Math.random()-.5)
function numQ(text,answer,hint,visual=null){const w=new Set();while(w.size<3){let x=Number(answer)+pick([-3,-2,-1,1,2,3]);if(x>=0&&x!==Number(answer))w.add(x)}return{text,answer,choices:shuffle([answer,...w]),hint,visual}}
function makeQuestion(t){let a,b,n,x;
switch(t){
case'count':n=rnd(1,10);return numQ('Có bao nhiêu chú gà con?',n,'Chạm và đếm từng bạn nhé!',{type:'count',count:n});
case'beforeAfter10':n=rnd(1,9);return Math.random()>.5?numQ(`Số liền sau của ${n} là?`,n+1,'Đếm thêm 1.'):numQ(`Số liền trước của ${n} là?`,n-1,'Đếm lùi 1.');
case'compose10':n=rnd(4,10);a=rnd(1,n-1);return numQ(`${n} gồm ${a} và mấy?`,n-a,'Tìm phần còn thiếu.');
case'count20':n=rnd(10,19);return numQ(`Số nào đứng ngay sau ${n}?`,n+1,'Đếm tiếp một số.');
case'compare':a=rnd(0,20);b=rnd(0,20);return{text:`${a} __ ${b}`,answer:a===b?'=':a>b?'>':'<',choices:['<','=','>'],hint:'Số ở bên phải trục số lớn hơn.',visual:{type:'line',a,b}};
case'order20':{let v=shuffle([rnd(0,20),rnd(0,20),rnd(0,20)]);let ans=Math.min(...v);return{text:`Số bé nhất trong ${v.join(', ')} là?`,answer:ans,choices:shuffle([...new Set([...v,Math.max(...v)+1])]),hint:'Tìm số nằm bên trái nhất trên trục số.'}}
case'add10':a=rnd(1,7);b=rnd(1,10-a);return numQ(`${a} + ${b} = ?`,a+b,'Gộp hai nhóm rồi đếm.',{type:'groups',a,b});
case'missingAdd10':a=rnd(1,6);n=rnd(a+1,10);return numQ(`${a} + ? = ${n}`,n-a,'Đếm từ số đầu đến tổng.');
case'storyAdd10':a=rnd(1,5);b=rnd(1,5);return numQ(`Lan có ${a} quả bóng, mẹ cho thêm ${b} quả. Lan có tất cả bao nhiêu quả?`,a+b,'“Cho thêm” nghĩa là cộng.');
case'sub10':a=rnd(2,10);b=rnd(1,a);return numQ(`${a} − ${b} = ?`,a-b,'Bớt đi rồi đếm số còn lại.');
case'missingSub10':a=rnd(3,10);b=rnd(0,a-1);return numQ(`${a} − ? = ${b}`,a-b,'Dùng phép cộng ngược để tìm.');
case'storySub10':a=rnd(4,10);b=rnd(1,a-1);return numQ(`Có ${a} chú chim, ${b} chú bay đi. Còn lại bao nhiêu chú?`,a-b,'“Bay đi” nghĩa là bớt đi.');
case'add20':a=rnd(5,15);b=rnd(1,20-a);return numQ(`${a} + ${b} = ?`,a+b,'Có thể tạo thành 10 trước.');
case'sub20':a=rnd(10,20);b=rnd(1,a);return numQ(`${a} − ${b} = ?`,a-b,'Đếm lùi hoặc tách số.');
case'mixed20':a=rnd(1,15);b=rnd(1,Math.min(8,a));return Math.random()>.5?numQ(`${a} + ${b} = ?`,a+b,'Nhìn kỹ dấu cộng.'):numQ(`${a} − ${b} = ?`,a-b,'Nhìn kỹ dấu trừ.');
case'shapes1':x=pick([{q:'Hình nào có 3 cạnh?',a:'Tam giác'},{q:'Hình nào không có góc?',a:'Hình tròn'},{q:'Hình nào có 4 cạnh bằng nhau?',a:'Hình vuông'}]);return{text:x.q,answer:x.a,choices:shuffle(['Tam giác','Hình tròn','Hình vuông','Hình chữ nhật']),hint:'Đếm cạnh và góc.',visual:{type:'shapes'}};
case'position1':return pick([{text:'🐱   🐶\nCon mèo ở phía nào của con chó?',answer:'Bên trái',choices:['Bên trái','Bên phải','Phía trên','Phía dưới'],hint:'Nhìn từ trái sang phải.'},{text:'⭐\n\n🎈\nNgôi sao ở đâu so với quả bóng?',answer:'Phía trên',choices:['Phía trên','Phía dưới','Bên trái','Bên phải'],hint:'Quan sát theo chiều dọc.'}]);
case'length1':a=rnd(2,6);b=rnd(a+1,9);return{text:`Bút A dài ${a} ô. Bút B dài ${b} ô. Bút nào dài hơn?`,answer:'Bút B',choices:['Bút A','Bút B','Bằng nhau'],hint:'Số ô lớn hơn nghĩa là dài hơn.'};
case'time1':n=rnd(1,12);return{text:'Đồng hồ đang chỉ mấy giờ?',answer:`${n} giờ`,choices:shuffle([`${n} giờ`,`${n%12+1} giờ`,`${Math.max(1,n-1)} giờ`,`${n}:30`]),hint:'Kim phút ở 12 là giờ đúng.',visual:{type:'clock',hour:n}};
case'chooseOperation1':a=rnd(2,8);b=rnd(1,Math.min(a,4));return Math.random()>.5?{text:`Có ${a} bông hoa, thêm ${b} bông. Chọn phép tính đúng.`,answer:`${a} + ${b}`,choices:[`${a} + ${b}`,`${a} − ${b}`],hint:'“Thêm” → cộng.'}:{text:`Có ${a} cái kẹo, cho đi ${b} cái. Chọn phép tính đúng.`,answer:`${a} − ${b}`,choices:[`${a} + ${b}`,`${a} − ${b}`],hint:'“Cho đi” → trừ.'};
case'wordMix1':a=rnd(3,10);b=rnd(1,a-1);return Math.random()>.5?numQ(`Mai có ${a} nhãn vở, được tặng thêm ${b}. Mai có bao nhiêu nhãn vở?`,a+b,'Tìm từ chỉ thêm vào.'):numQ(`Có ${a} chiếc bánh, ăn ${b} chiếc. Còn bao nhiêu chiếc?`,a-b,'Tìm số còn lại.');
case'placeValue':a=rnd(1,9);b=rnd(0,9);n=rnd(0,9);return numQ(`${a}${b}${n} có chữ số hàng chục là?`,b,'Hàng chục ở giữa.');case'compare1000':a=rnd(100,999);b=rnd(100,999);return{text:`${a} __ ${b}`,answer:a>b?'>':a<b?'<':'=',choices:['<','=','>'],hint:'So sánh hàng trăm trước.'};case'addSub1000':a=rnd(100,600);b=rnd(10,200);return numQ(`${a} + ${b} = ?`,a+b,'Đặt tính thẳng hàng.');case'mul25':a=pick([2,5]);b=rnd(1,10);return numQ(`${a} × ${b} = ?`,a*b,`Nhớ bảng ${a}.`);case'length2':a=rnd(1,5);return numQ(`${a} m = ? cm`,a*100,'1 m = 100 cm.');case'money2':a=pick([5000,10000]);return numQ(`Có 20.000đ, mua món ${a.toLocaleString('vi-VN')}đ. Còn?`,20000-a,'Lấy tiền có trừ tiền mua.');case'large3':case'large4':a=rnd(1000,9000);b=rnd(100,900);return numQ(`${a} + ${b} = ?`,a+b,'Đặt tính.');case'muldiv3':a=rnd(2,9);b=rnd(2,9);return numQ(`${a} × ${b} = ?`,a*b,'Bảng nhân.');case'area3':a=rnd(2,9);b=rnd(2,9);return numQ(`HCN dài ${a}cm, rộng ${b}cm. Diện tích?`,a*b,'Dài × rộng.');case'fraction4':return{text:'1/4 + 2/4 = ?',answer:'3/4',choices:['3/4','3/8','2/4','1/2'],hint:'Cùng mẫu thì cộng tử.'};case'average4':return numQ('Trung bình của 10, 20, 30?',20,'Cộng rồi chia 3.');case'decimal5':return numQ('1.5 + 2.5 = ?',4,'Đặt dấu phẩy thẳng cột.');case'percent5':return numQ('20% của 100?',20,'20 trên 100.');case'motion5':return numQ('Đi 20 km/h trong 3 giờ. Quãng đường?',60,'Vận tốc × thời gian.');default:return numQ('2 + 2 = ?',4,'Đếm thêm 2.')}}
function Clock({hour}){return <div className="kid-clock"><div className="clock-hand hour" style={{transform:`translateX(-50%) rotate(${hour*30}deg)`}}/><div className="clock-hand minute"/><div className="clock-dot"/>{[12,3,6,9].map(n=><span key={n} className={`clock-n n${n}`}>{n}</span>)}</div>}
function Visual({v}){const[tap,setTap]=useState([]);if(!v)return null;if(v.type==='count')return <div className="count-play">{Array.from({length:v.count},(_,i)=><button key={i} className={tap.includes(i)?'counted':''} onClick={()=>setTap(s=>s.includes(i)?s:[...s,i])}>🐥<small>{tap.includes(i)?tap.indexOf(i)+1:''}</small></button>)}</div>;if(v.type==='groups')return <div className="group-visual"><div>{'🍎'.repeat(v.a)}</div><b>+</b><div>{'🍏'.repeat(v.b)}</div></div>;if(v.type==='line')return <div className="learn-numberline">{Array.from({length:21},(_,i)=><span key={i}>{i}</span>)}</div>;if(v.type==='clock')return <Clock hour={v.hour}/>;if(v.type==='shapes')return <div className="shape-showcase"><span className="shape circle"/><span className="shape triangle"/><span className="shape square"/><span className="shape rectangle"/></div>;return null}
const empty={stars:0,bestStreak:0,solved:0,correct:0,completedLessons:{},lessonScores:{}};function load(){try{return{...empty,...JSON.parse(localStorage.getItem('math-kid-progress'))}}catch{return empty}}
export default function App(){const[screen,setScreen]=useState('home'),[level,setLevel]=useState(1),[chapterId,setChapter]=useState(null),[lessonId,setLesson]=useState(null),[q,setQ]=useState(null),[sel,setSel]=useState(null),[hint,setHint]=useState(false),[streak,setStreak]=useState(0),[progress,setProgress]=useState(load),[quiz,setQuiz]=useState({index:0,score:0,total:5}),[sound,setSound]=useState(true);useEffect(()=>localStorage.setItem('math-kid-progress',JSON.stringify(progress)),[progress]);const lv=useMemo(()=>curriculum.find(x=>x.level===level),[level]),ch=lv?.chapters.find(x=>x.id===chapterId),lesson=ch?.lessons.find(x=>x.id===lessonId),correct=sel!==null&&String(sel)===String(q?.answer),accuracy=progress.solved?Math.round(progress.correct/progress.solved*100):0;const Back=({to})=><button className="icon-button" onClick={()=>setScreen(to)}><ChevronLeft/></button>;function begin(mode){setQ(makeQuestion(lesson.practice));setSel(null);setHint(false);if(mode==='quiz')setQuiz({index:0,score:0,total:5});setScreen(mode)}function answer(c){if(sel!==null)return;setSel(c);let ok=String(c)===String(q.answer),s=ok?streak+1:0;setStreak(s);setProgress(p=>({...p,stars:p.stars+(ok?1:0),solved:p.solved+1,correct:p.correct+(ok?1:0),bestStreak:Math.max(p.bestStreak,s)}));if(screen==='quiz'&&ok)setQuiz(z=>({...z,score:z.score+1}))}function next(){if(screen==='quiz'&&quiz.index+1>=quiz.total){setProgress(p=>({...p,completedLessons:{...p.completedLessons,[lessonId]:true},lessonScores:{...p.lessonScores,[lessonId]:Math.max(p.lessonScores?.[lessonId]||0,quiz.score)}}));setScreen('result');return}if(screen==='quiz')setQuiz(z=>({...z,index:z.index+1}));setQ(makeQuestion(lesson.practice));setSel(null);setHint(false)}
if(screen==='level')return <main className="app-shell inner-shell"><header className="topbar"><Back to="home"/><div className="practice-title"><span>{lv.emoji}</span><div><small>{lv.grade}</small><strong>{lv.title}</strong></div></div><div className="stats-pill"><Star size={17}/> {progress.stars}</div></header><section className="inner-content"><div className="page-heading"><small>LEVEL {level}</small><h1>Chọn chủ đề</h1><p>{level===1?'Luyện từng kỹ năng nhỏ, phù hợp bé lớp 1.':'Học từng phần nhỏ và làm quiz.'}</p></div><div className="chapter-grid">{lv.chapters.map(c=><button className="chapter-card" key={c.id} onClick={()=>{setChapter(c.id);setScreen('chapter')}}><span>{c.icon}</span><div><h3>{c.name}</h3><p>{c.note}</p><small>{c.lessons.length} bài luyện</small></div><b>→</b></button>)}</div></section></main>;
if(screen==='chapter')return <main className="app-shell inner-shell"><header className="topbar"><Back to="level"/><div className="practice-title"><span>{ch.icon}</span><div><small>{lv.grade}</small><strong>{ch.name}</strong></div></div></header><section className="inner-content"><div className="page-heading"><small>CHỦ ĐỀ</small><h1>{ch.name}</h1><p>{ch.note}</p></div><div className="lesson-list">{ch.lessons.map((l,i)=><button className="lesson-row" key={l.id} onClick={()=>{setLesson(l.id);setScreen('learn')}}><span className="lesson-index">{progress.completedLessons?.[l.id]?<CheckCircle2/>:i+1}</span><div><h3>{l.title}</h3><p>{progress.completedLessons?.[l.id]?`Đã hoàn thành · ${progress.lessonScores?.[l.id]||0}/5`:'Học nhanh → luyện tập → quiz'}</p></div><b>→</b></button>)}</div></section></main>;
if(screen==='learn')return <main className="app-shell inner-shell"><header className="topbar"><Back to="chapter"/><div className="practice-title"><span>📘</span><div><small>BÀI LUYỆN</small><strong>{lesson.title}</strong></div></div></header><section className="learn-card"><div className="learn-hero">{ch.icon}</div><small>NHỚ NHÉ</small><h1>{lesson.title}</h1><div className="concept-list">{lesson.learn.map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p></div>)}</div><div className="learn-actions"><button className="secondary" onClick={()=>begin('practice')}>🎯 Luyện không giới hạn</button><button className="primary" onClick={()=>begin('quiz')}>Quiz 5 câu <Sparkles size={18}/></button></div></section></main>;
if(screen==='practice'||screen==='quiz')return <main className="app-shell practice-shell"><header className="topbar"><Back to="learn"/><div className="practice-title"><span>{ch.icon}</span><div><small>{screen==='quiz'?`QUIZ ${quiz.index+1}/5`:'LUYỆN TẬP'}</small><strong>{lesson.title}</strong></div></div><div className="streak"><Flame size={20}/> {streak}</div></header><section className="question-card"><div className="question-badge"><Sparkles size={16}/> Câu hỏi mới</div><h1 style={{whiteSpace:'pre-line'}}>{q.text}</h1><Visual v={q.visual}/><p>Chọn đáp án đúng</p><div className="answer-grid">{q.choices.map(c=>{let s='';if(sel!==null&&String(c)===String(q.answer))s='correct';else if(sel!==null&&String(c)===String(sel))s='wrong';return <button key={String(c)} className={`answer ${s}`} onClick={()=>answer(c)}>{c}</button>})}</div>{sel===null?<button className="hint-button" onClick={()=>setHint(!hint)}><Lightbulb size={16}/> {hint?q.hint:'Gợi ý cho bé'}</button>:<div className={`feedback ${correct?'yay':'oops'}`}><div><strong>{correct?'Tuyệt vời! 🌟':'Thử lại ở câu sau nhé! 💪'}</strong><span>{correct?'Con nhận 1 ngôi sao.':`Đáp án đúng: ${q.answer}`}</span></div><button onClick={next}>{screen==='quiz'&&quiz.index===4?'Xem kết quả':'Câu tiếp theo →'}</button></div>}</section></main>;
if(screen==='result')return <main className="app-shell result-shell"><section className="result-card"><Trophy size={58}/><small>HOÀN THÀNH</small><h1>{quiz.score}/5</h1><p>{quiz.score>=4?'Xuất sắc! Con làm rất tốt! 🌟':'Mình luyện thêm một lượt nữa nhé! 🌱'}</p><button className="primary" onClick={()=>begin('quiz')}><RotateCcw size={18}/> Làm lại</button><button className="secondary" onClick={()=>setScreen('chapter')}>Chọn bài khác</button></section></main>;
if(screen==='parent')return <main className="app-shell inner-shell"><header className="topbar"><Back to="home"/><strong>Tiến độ học tập</strong></header><section className="inner-content"><div className="dashboard-grid"><div className="dash-card"><Star/><b>{progress.stars}</b><span>Ngôi sao</span></div><div className="dash-card"><BarChart3/><b>{accuracy}%</b><span>Chính xác</span></div><div className="dash-card"><CheckCircle2/><b>{Object.keys(progress.completedLessons||{}).length}</b><span>Bài hoàn thành</span></div></div></section></main>;
return <main className="app-shell"><nav className="nav"><div className="brand"><span>✦</span><div><strong>Math Adventure</strong><small>Học Toán thật vui!</small></div></div><div className="nav-actions"><button onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}</button><button onClick={()=>setScreen('parent')}><BarChart3/> Phụ huynh</button></div></nav><section className="hero"><div className="hero-copy"><div className="eyebrow">✨ MỖI NGÀY MỘT CHÚT</div><h1>Học Toán.<br/><span>Chơi thật vui!</span></h1><p>Level 1 đã có nhiều bài luyện theo từng kỹ năng dành cho học sinh lớp 1.</p><div className="hero-stats"><div><Star/><b>{progress.stars}</b><span>Ngôi sao</span></div><div><Flame/><b>{progress.bestStreak}</b><span>Chuỗi tốt nhất</span></div></div></div><div className="mascot-card">🦊<div>Hôm nay mình học gì nhỉ?</div></div></section><section className="levels-section"><div className="section-heading"><div><small>CHỌN TRÌNH ĐỘ</small><h2>Bắt đầu hành trình</h2></div></div><div className="level-grid">{curriculum.map(x=><button className={`level-card ${x.color}`} key={x.level} onClick={()=>{setLevel(x.level);setChapter(null);setLesson(null);setScreen('level')}}><span className="level-emoji">{x.emoji}</span><small>LEVEL {x.level}</small><h3>{x.grade}</h3><p>{x.title}</p><div>Khám phá <b>→</b></div></button>)}</div></section></main>}
