export const smoothieIngredients = [
  {name:'Dâu tây',icon:'🍓',group:'fruit'},
  {name:'Chuối',icon:'🍌',group:'fruit'},
  {name:'Xoài',icon:'🥭',group:'fruit'},
  {name:'Dứa',icon:'🍍',group:'fruit'},
  {name:'Táo đỏ',icon:'🍎',group:'fruit'},
  {name:'Cam',icon:'🍊',group:'fruit'},
  {name:'Nho tím',icon:'🍇',group:'fruit'},
  {name:'Kiwi',icon:'🥝',group:'fruit'},
  {name:'Dưa hấu',icon:'🍉',group:'fruit'},
  {name:'Dưa lưới',icon:'🍈',group:'fruit'},
  {name:'Đào',icon:'🍑',group:'fruit'},
  {name:'Lê',icon:'🍐',group:'fruit'},
  {name:'Cherry',icon:'🍒',group:'fruit'},
  {name:'Việt quất',icon:'🫐',group:'fruit'},
  {name:'Bơ',icon:'🥑',group:'fruit'},
  {name:'Dừa',icon:'🥥',group:'fruit'},
  {name:'Thanh long',icon:'🐉',group:'fruit'},
  {name:'Chanh dây',icon:'🟣',group:'fruit'},
  {name:'Ổi',icon:'🍐',group:'fruit'},
  {name:'Đu đủ',icon:'🧡',group:'fruit'},
  {name:'Mận',icon:'🟣',group:'fruit'},
  {name:'Lựu',icon:'🔴',group:'fruit'},
  {name:'Vải',icon:'🔴',group:'fruit'},
  {name:'Măng cụt',icon:'🟣',group:'fruit'},
  {name:'Mít',icon:'🟡',group:'fruit'},

  {name:'Sữa tươi',icon:'🥛',group:'base'},
  {name:'Sữa chua',icon:'🥣',group:'base'},
  {name:'Sữa đặc',icon:'🥛',group:'base'},
  {name:'Sữa hạt',icon:'🥛',group:'base'},
  {name:'Nước dừa',icon:'🥥',group:'base'},
  {name:'Nước lọc',icon:'💧',group:'base'},

  {name:'Đường trắng',icon:'🍬',group:'extra'},
  {name:'Đường nâu',icon:'🟤',group:'extra'},
  {name:'Mật ong',icon:'🍯',group:'extra'},
  {name:'Đá viên',icon:'🧊',group:'extra'},
  {name:'Hạt chia',icon:'🌱',group:'extra'},
  {name:'Yến mạch',icon:'🌾',group:'extra'},
  {name:'Bột cacao',icon:'🍫',group:'extra'},
  {name:'Bơ đậu phộng',icon:'🥜',group:'extra'},
  {name:'Kem tươi',icon:'🍦',group:'extra'},
  {name:'Vanilla',icon:'🌼',group:'extra'}
]

export const ingredientGroups = [
  {id:'fruit',label:'🍓 25 loại trái cây'},
  {id:'base',label:'🥛 Sữa & nền'},
  {id:'extra',label:'🧊 Phụ liệu'}
]
